language: python
python: 3.5
sudo: false

branches:
    only:
        - master
        - /^\d\.\d+$/

before_install:
    # Autologin
    - pip install -U pip wheel
    - git clone https://github.com/TeamHG-Memex/autologin.git
    - pip install -r autologin/requirements.txt --no-binary Formasaurus
    - python -c "import formasaurus; formasaurus.extract_forms('a')"
    - cd autologin && python setup.py install && cd -
    - autologin-http-api &

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip

